// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type Game struct {
	ID        int64
	Game      string
	Year      interface{}
	Dev       string
	Publisher string
	Platform  string
}
